project_id = "lp-helena-joias"

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54330
major_version = 17

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[auth]
enabled = true
enable_signup = false

[storage]
enabled = true
file_size_limit = "8MiB"
