from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REQUIRED_FINDING_KEYS = {
    "id",
    "category",
    "page_file",
    "problem",
    "evidence",
    "consequence",
    "priority",
    "impact",
    "effort",
    "recommended_fix",
    "validation",
}


def load_report(path: str) -> dict[str, Any]:
    candidate = Path(path)
    if not candidate.exists():
        raise FileNotFoundError(f"Report file does not exist: {path}")
    try:
        data = json.loads(candidate.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Report is not valid JSON: {exc.msg}") from exc
    if not isinstance(data, dict):
        raise ValueError("Report root must be a JSON object.")
    return data


def validate_report(data: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    findings = data.get("findings")
    if findings is None:
        errors.append("Missing findings array.")
        return errors
    if not isinstance(findings, list):
        errors.append("findings must be an array.")
        return errors
    for index, finding in enumerate(findings):
        if not isinstance(finding, dict):
            errors.append(f"findings[{index}] must be an object.")
            continue
        missing = sorted(REQUIRED_FINDING_KEYS - set(finding))
        if missing:
            errors.append(f"findings[{index}] missing keys: {', '.join(missing)}")
        for key in REQUIRED_FINDING_KEYS:
            if key in finding and finding[key] in ("", None):
                errors.append(f"findings[{index}].{key} is empty.")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate that a SEO audit JSON report contains actionable finding fields.")
    parser.add_argument("report", help="Path to a JSON report generated by audit_page.py --format json.")
    args = parser.parse_args()
    try:
        errors = validate_report(load_report(args.report))
    except (FileNotFoundError, ValueError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1
    print("SEO report is valid.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
